# Generated by Django 5.1.6 on 2025-08-21 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=20, unique=True)),
                ('user_name', models.CharField(max_length=255)),
                ('barangay', models.CharField(max_length=120)),
                ('complaint_type', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('image_base64', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Reported', 'Reported'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Declined', 'Declined')], default='Reported', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_transactions', to=settings.AUTH_USER_MODEL)),
                ('complaint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='myapp.complaint')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
