# Generated by Django 5.1.6 on 2025-08-21 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_fix_transaction_complaint_relationship'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
