# Generated by Django 5.1.6 on 2025-08-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_add_profile_picture_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.TextField(blank=True, null=True, help_text='Store base64 image data'),
        ),
    ]
