# Generated by Django 5.1.6 on 2025-08-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_fix_profile_picture_field'),
    ]

    operations = [
        migrations.RunSQL(
            # SQL to alter the column type to TEXT
            "ALTER TABLE myapp_userprofile ALTER COLUMN profile_picture TYPE TEXT;",
            # Reverse SQL (if needed)
            "ALTER TABLE myapp_userprofile ALTER COLUMN profile_picture TYPE VARCHAR(255);"
        ),
    ]
