# Generated by Django 5.1.6 on 2025-08-27 14:52
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_force_profile_picture_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='user_barangay',
            field=models.CharField(blank=True, max_length=120, null=True, help_text='Store user\'s barangay for admin view'),
        ),
    ]
