# Generated by Django 5.1.6 on 2025-08-27 23:10
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_add_user_barangay_to_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='resolution_image',
            field=models.TextField(blank=True, null=True, help_text='Base64 image showing evidence of resolution'),
        ),
    ]

