# Generated by Django 5.1.6 on 2025-09-04 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_add_is_read_to_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Declined/Spam', 'Declined/Spam')], default='Pending', max_length=20),
        ),
    ]
