# Generated by Django 5.1.6 on 2025-09-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_auto_20250904_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='admin_update',
            field=models.TextField(blank=True, help_text='Admin-provided update when status is In Progress', null=True),
        ),
    ]
