# Generated by Django 5.1.6 on 2025-09-19 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_add_full_name_to_admin_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminprofile',
            name='full_name',
        ),
    ]
