# Generated by Django 5.1.6 on 2025-09-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_add_admin_activity_logging'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='forward_date',
            field=models.DateTimeField(blank=True, help_text='Date when complaint was forwarded', null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='forward_reason',
            field=models.TextField(blank=True, help_text='Reason for forwarding to higher agency', null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='forwarded_to_agency',
            field=models.CharField(blank=True, help_text='Agency where complaint was forwarded', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='adminactivitylog',
            name='action_type',
            field=models.CharField(choices=[('status_change', 'Status Change'), ('chat_message', 'Chat Message'), ('complaint_view', 'Complaint View'), ('user_management', 'User Management'), ('complaint_forward', 'Complaint Forward')], max_length=20),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Declined/Spam', 'Declined/Spam'), ('Forwarded to Agency', 'Forwarded to Agency'), ('Resolved by Agency', 'Resolved by Agency')], default='Pending', max_length=30),
        ),
    ]
