# Generated by Django 5.1.6 on 2025-09-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_complaint_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='barangay_captain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='barangay_kagawad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='barangay_secretary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='sk_chairman',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='term_end_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='term_start_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
