# Generated by Django 5.1.6 on 2025-11-02 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_adminprofile_barangay_captain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='User phone number for SMS notifications (format: 09123456789)', max_length=15, null=True),
        ),
    ]
